name: flutter_udid
description: Plugin to retrieve a persistent UDID accross reinstalls on iOS and Android
version: 2.0.0
author: Leon Kukuk <leon@kukuk.me>
homepage: https://github.com/GigaDroid/flutter_udid

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0

flutter:
  plugin:
    androidPackage: de.gigadroid.flutterudid
    pluginClass: FlutterUdidPlugin
